### ISSUE TITLE
not working wth OLED Featherwing on nrf52840

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/Adafruit_CircuitPython_SSD1306#15]
I just tried running the test  cases on a particle argon (nrf52840) with an OLED featherwing and I just get a screen full of random pixels. The same code works fine on a metro_m4 _express

All of the test cases (bouncing bali,simpletest and ssd1306_framebuftest have the same results so it is not just framebuf)
Note -- the default nrf builds still include the "built in" framebuf  but I tried it with they built-in and the new adafruit_framebuf.py -- same results.

I have not test other nrf52840 boards yet.

also note, there is no RESET pin for the OLED Featherwing.

**Comment by jerryneedell** [comment]
It works fine with the SPI interface to a 128x32 SPI OLED -- just not working with I2C to the featherwing -- SPI does have a RESET so that may be the issue although the same board works fine on the metro_m4_express -- is there a way to get a RESET signal to the OLED featherwing? Looks like the SSD1306 reset on the OLED Featherwing is tied to board RESET -- I suppose some jumpering could be worked out if this seems like the issue.

**Comment by deshipu** [comment]
Can you verify that it works after you press the reset button on the wing manually?

**Comment by jerryneedell** [comment]
It does not. That also resets the argon.

**Comment by jerryneedell** [comment]
I will try later with the boards separated.

**Comment by jerryneedell** [comment]
separating the boards and pressing RESET or setting the RESET pin to a GPIO pin and passing it to the configuration makes no difference - still just a lot of white pixels.

**Comment by jerryneedell** [comment]
I verified the same behavior on a PCA10056.

**Comment by ladyada** [comment]
closing this in favor of the https://github.com/adafruit/circuitpython/issues/1422
