### ISSUE TITLE
Examples: no clear instructions on where to get depended PIL library and/or no separate example  on text display

### ISSUE THREAD

**Issue by peppekerstens** [adafruit/Adafruit_CircuitPython_SSD1306#27]
issue text should be clear enough (i hope) :)

**Comment by ladyada** [comment]
@kattni please add a note to the top of the linux examples that they are for linux!

**Comment by peppekerstens** [comment]
@ladyada and @kattni ; I am sorry, should have RTFM better;  after re-reading, the examples clearly say that they are for Linux.... :|

Would still be nice to include a example on how to accomplish text on 'pure' CircuitPython devices.  :)

**Comment by ladyada** [comment]
https://github.com/adafruit/Adafruit_CircuitPython_SSD1306/blob/master/examples/ssd1306_framebuftest.py

https://learn.adafruit.com/adafruit-oled-featherwing/circuitpython-and-python-usage#text-8-27

**Comment by kattni** [comment]
I took a look at it and found they had a note already as well. Glad we figured it out!

Closing.
