### ISSUE TITLE
Text Size for Adafruit_CircuitPython_SSD1306/examples/ssd1306_stats.py

### ISSUE THREAD

**Issue by mrsstaceyseigle** [adafruit/Adafruit_CircuitPython_SSD1306#42]
I have ip address being displayed only from the example SSD1306_stats.py
the text is very small how do we increase. 

Adafruit_CircuitPython_SSD1306/examples/ssd1306_stats.py

**Comment by ladyada** [comment]
hi @mrsstaceyseigle github issues are not a good place for tech support. if you purchased from adafruit please post in the forums.
