### ISSUE TITLE
Using the download functions from the target produces the word "download" as the download

### ISSUE THREAD

**Issue by DoctorWho8** [adafruit/Adafruit_CircuitPython_SSD1306#47]
Hello!
I have that file, "stats.py" running on an OLED attached to a Pi Zero WH. I needed to screenscrape a raw text of the file and paste that into the editor, because using the download methods, such as pointing the wget command to the URL that corresponds to the code did exactly the same as the subject, on a Pi3A board running the same release of PiOS and the tools described on the same page as [https://learn.adafruit.com/adafruit-pioled-128x32-mini-oled-for-raspberry-pi?view=all](url) 

But if were to cause the download function to happen here on Windows, it would work. If I had a browser running on a desktop on that Pi Zero WH it would work.  We are expected to send the code to our devices when seeing the prompt inside a terminal window such as Putty. So we should have the benefit of a doubt and believe that our download tools would also work.

**Comment by ladyada** [comment]
hi, yes thats why we recommend copy & pasting it, most people are ssh'd in anyways
https://learn.adafruit.com/adafruit-pioled-128x32-mini-oled-for-raspberry-pi?view=all#verify-i2c-device-3024321-11
