### ISSUE TITLE
Example code not helpful - draws black on black

### ISSUE THREAD

**Issue by herrmanthegerman** [adafruit/Adafruit_CircuitPython_SSD1306#50]
I assume that the example code given on _README.rst_ should be considered a "smoke test" or "hello world" program to enable the user to check that his/her display can be addressed and is basically working.

That said, with executing `display.fill(0)` it draws a black background on my black display. I didn't see any change at all. 

I suggest to change this to `display.fill(1)` so it draws some other "color" than black on the display. At least this works for my SSD1306 OLED display.

Does that make sense?

**Comment by ladyada** [comment]
sure, please submit a PR to revise it!

**Comment by desertsagebrush** [comment]
This should be fixed now, by mirroring the code in `examples/ssd1306_simpletest.py`.
