### ISSUE TITLE
SPI mode has been broken with the last set of commits 'AttributeError SSD1306_SPI has no object page_address'

### ISSUE THREAD

**Issue by dattrax** [adafruit/Adafruit_CircuitPython_SSD1306#58]
I got it back working by adding

self.page_addressing = page_addressing

in the SSD1306_SPI class

**Comment by adamcandy** [comment]
Hi @dattrax, thanks very much for pointing this out.  Great you have been able to test the new updates with SPI displays -- and sorry that the new page addressing code has broken use of the SPI class.
I agree your suggested fix is appropriate and the best solution.  This is implemented in pull request #59.

**Comment by adamcandy** [comment]
It would be interesting to hear if there are any SPI displays that do not work with horizontal addressing mode and may also need use of page addressing instead.
