### ISSUE TITLE
Usage Example code requires two runs on Pico using Thonny before screen actually updates

### ISSUE THREAD

**Issue by roryjamesallen** [adafruit/Adafruit_CircuitPython_SSD1306#70]
When running the example code (or seemingly any code using the module) on a Raspberry Pi Pico using Thonny IDE the code must be run twice before any changes to the display made in code are visible on screen.
It consistently is exactly 2 runs before changes are visible, and the changes are always visible after 2.

I have tried implementing a delay both before the refresh, and before a second code refresh, and neither fix the issue.

![image](https://user-images.githubusercontent.com/79809962/140646944-dac373cf-659d-48f5-b41b-edfc4d010a7a.png)

**Comment by tannewt** [comment]
Does this occur when you use Mu or another editor? Thonny loads code in a unique way that may be causing this.

**Comment by roryjamesallen** [comment]
That fixed it, thank you!
