### ISSUE TITLE
Adafruit_SSD1306 library not working on micropython with blinka

### ISSUE THREAD

**Issue by Andrei631** [adafruit/Adafruit_CircuitPython_SSD1306#77]
I am trying to use a SSD1306 display with a raspberry pi pico w, and i can't get it to work because of this error:
![image](https://user-images.githubusercontent.com/36139150/194593057-6592d9d0-9001-4595-9ddd-8136aa90119c.png)
```
Line 70: super().__init__(buffer, width, height)
...
Line 327:  super().__init__(
Line 328:             memoryview(self.buffer),
Line 329:             width,
Line 330:             height,
Line 331:             external_vcc=external_vcc,
Line 332:             reset=reset,
Line 333:             page_addressing=self.page_addressing,
                 )
```

**Comment by tekktrik** [comment]
Looks like the `format` argument isn't given to MicroPython's `framebuf.FrameBuffer`, whereas it's auto-populated in CircuitPython.  I can submit a fix for this, would you be willing to test it for me?

**Comment by Andrei631** [comment]
> Looks like the `format` argument isn't given to MicroPython's `framebuf.FrameBuffer`, whereas it's auto-populated in CircuitPython.  I can submit a fix for this, would you be willing to test it for me?

Yeah, I am willing to test it.

**Comment by Andrei631** [comment]
I edited the `super().__init__(buffer, width, height)` to `super().__init__(buffer, width, height, framebuf.MVLSB)` and now it's working, thanks for the help!
