### ISSUE TITLE
please add support orange pi zore 3 (H618)

### ISSUE THREAD

**Issue by skyfsj** [adafruit/Adafruit_CircuitPython_SSD1306#82]
this gpio pinout
![image](https://github.com/adafruit/Adafruit_CircuitPython_SSD1306/assets/47785500/f16aa647-bdc1-4e81-bca4-fe732864d408)

board doc: https://drive.google.com/drive/folders/1pZ4X4uP2C7N_6wXU0TjAxC7U1eCG05L1

**Comment by tannewt** [comment]
This library is generic. Do you mean to add Blinka support? See this guide for how to do it: https://learn.adafruit.com/adding-a-single-board-computer-to-platformdetect-for-blinka
